### ISSUE TITLE
nserver.py aborts with "unexpected keyword argument 'flip_filters'"

### ISSUE THREAD

**Issue by voreiche** [tjwei/Quick-Neural-Art-Transfer#3]
I cannot start nserver.py it reports:

`(myenv) ubuntu@ip-172-31-15-252:~/Quick-Neural-Art-Transfer$ python nserver.py 
Using gpu device 0: GRID K520 (CNMeM is enabled with initial size: 75.0% of memory, cuDNN Version is too old. Update to v5, was 3007.)
/home/ubuntu/myenv/lib/python3.4/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
unable to import Conv2DDNNLayer, use Conv2DLayer instead
Traceback (most recent call last):
  File "nserver.py", line 3, in <module>
    import neuralStyle
  File "/home/ubuntu/Quick-Neural-Art-Transfer/neuralStyle.py", line 69, in <module>
    net = build_model()
  File "/home/ubuntu/Quick-Neural-Art-Transfer/neuralStyle.py", line 44, in build_model
    net['conv1_1'] = ConvLayer(net['input'], 64, 3, pad=1)
  File "/home/ubuntu/Quick-Neural-Art-Transfer/neuralStyle.py", line 35, in ConvLayer
    return ConvLayer0(*args, flip_filters=False, **kwargs)
  File "/home/ubuntu/myenv/lib/python3.4/site-packages/lasagne/layers/conv.py", line 391, in __init__
    super(Conv2DLayer, self).__init__(incoming, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'flip_filters'`

Any ideas? I'm using the latest version from git. I already fixed the type in `super(Conv2DLayer, self).__init__(incoming, **kw**e**args)` to `super(Conv2DLayer, self).__init__(incoming, **kwargs)`

Upgrading to cuDNN v5 does not help.

Any help welcome.

**Comment by tjwei** [comment]
My test environment was the bleeding edge install of lasagne and cudnn v4.
Install the bleeding edge version of theano and lasagne may fix the issue.

```
pip install --upgrade https://github.com/Theano/Theano/archive/master.zip
pip install --upgrade https://github.com/Lasagne/Lasagne/archive/master.zip
```

More detail
The message `unable to import Conv2DDNNLayer, use Conv2DLayer instead` indicates that it has   some troubles to import `Conv2DDNNLayer`
According to the message, your install of lasagane does not support filp_filters argument of `Conv2DLayer`, which is supported in lasagne 0.20dev1
I am not sure whether lasagne supports cudnn v5 yet but by modifying the following code in neuralStyle.py

```
try:
    from lasagne.layers.dnn import Conv2DDNNLayer as ConvLayer
except:
    print("unable to import Conv2DDNNLayer, use Conv2DLayer instead")
    from lasagne.layers import Conv2DLayer as ConvLayer0
    def ConvLayer(*args, **kwargs):
        return ConvLayer0(*args, flip_filters=False, **kweargs)
```

to

```
from lasagne.layers.dnn import Conv2DDNNLayer as ConvLayer
```

It will tell us more information to figure out what the issue is.

**Comment by voreiche** [comment]
tjwei

I’ve taken the proposed actions und documented the results:
`Collecting https://github.com/Theano/Theano/archive/master.zip
  Downloading https://github.com/Theano/Theano/archive/master.zip (9.8MB)
Collecting numpy>=1.7.1 (from Theano==0.9.0dev0)
  Downloading numpy-1.11.0-cp34-cp34m-manylinux1_x86_64.whl (15.5MB)
Collecting scipy>=0.11 (from Theano==0.9.0dev0)
  Downloading scipy-0.17.0-cp34-cp34m-manylinux1_x86_64.whl (39.3MB)
Collecting six>=1.9.0 (from Theano==0.9.0dev0)
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: numpy, scipy, six, Theano
  Found existing installation: six 1.5.2
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.5.2:
      Successfully uninstalled six-1.5.2
  Running setup.py install for Theano ... done
Successfully installed Theano-0.9.0.dev0 numpy-1.11.0 scipy-0.17.0 six-1.10.0`

`ubuntu@ip-172-31-15-252:~$ sudo -H "PATH=$PATH" pip install --upgrade https://github.com/Lasagne/Lasagne/archive/master.zip
Collecting https://github.com/Lasagne/Lasagne/archive/master.zip
  Downloading https://github.com/Lasagne/Lasagne/archive/master.zip (202kB)
Requirement already up-to-date: numpy in /usr/local/lib/python3.4/dist-packages (from Lasagne==0.2.dev1)
Installing collected packages: Lasagne
  Running setup.py install for Lasagne ... done
Successfully installed Lasagne-0.2.dev1`

Installed cuDNN v4 which gives
`(myenv) ubuntu@ip-172-31-15-252:~/cuda/lib64$ ls -al
total 226120
drwxrwxr-x 2 ubuntu ubuntu     4096 May  4 09:54 .
drwxrwxr-x 4 ubuntu ubuntu     4096 May  3 15:40 ..
lrwxrwxrwx 1 ubuntu ubuntu       13 Feb  9 17:48 libcudnn.so -> libcudnn.so.4
lrwxrwxrwx 1 ubuntu ubuntu       17 Feb  9 17:48 libcudnn.so.4 -> libcudnn.so.4.0.7
-rwxrwxr-x 1 ubuntu ubuntu 61453024 Feb  8 22:12 libcudnn.so.4.0.7
lrwxrwxrwx 1 ubuntu ubuntu       17 Mar 22 07:44 libcudnn.so.5 -> libcudnn.so.5.0.4
-rwxrwxr-x 1 ubuntu ubuntu 59823168 Mar 22 01:37 libcudnn.so.5.0.4
lrwxrwxrwx 1 ubuntu ubuntu       18 Aug 21  2015 libcudnn.so.7.0 -> libcudnn.so.7.0.64
-rwxrwxr-x 1 ubuntu ubuntu 48217000 Aug 21  2015 libcudnn.so.7.0.64
-rw-rw-r-- 1 ubuntu ubuntu 62025862 Feb  8 22:12 libcudnn_static.a`

libcudnn.so is linked to libcudnn.so.4 which is correct.

`(myenv) ubuntu@ip-172-31-15-252:~/Quick-Neural-Art-Transfer$ python nserver.py
/home/ubuntu/myenv/lib/python3.4/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
Traceback (most recent call last):
  File "nserver.py", line 3, in <module>
    import neuralStyle
  File "/home/ubuntu/Quick-Neural-Art-Transfer/neuralStyle.py", line 37, in <module>
    from lasagne.layers.dnn import Conv2DDNNLayer as ConvLayer
  File "/home/ubuntu/myenv/lib/python3.4/site-packages/lasagne/layers/dnn.py", line 13, in <module>
    raise ImportError("dnn not available")  # pragma: no cover
ImportError: dnn not available`

My Python is at version
`(myenv) ubuntu@ip-172-31-15-252:~/cuda/lib64$ python --version
Python 3.4.3`

It seems as if cuDNN is not available, although its installed.

kind regards
Volker

**Comment by tjwei** [comment]
Seems to be a theano configuration issue.
The discussion of this issue https://github.com/Lasagne/Lasagne/issues/470 might be useful.

**Comment by voreiche** [comment]
cuDNN seems to be available since
`(myenv) ubuntu@ip-172-31-15-252:~$ python -c 'from theano.sandbox.cuda import dnn_available; print( dnn_available()) ; print(dnn_available.msg)'
Using gpu device 0: GRID K520 (CNMeM is disabled, cuDNN 4007)
True
None`
reports True.

**Comment by tjwei** [comment]
It seems your python still using an old version of lasagne.
line 13 of the new version of dnn.py looks like https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/dnn.py

It changes in this commit https://github.com/Lasagne/Lasagne/commit/31d325cac31b53c97b79f1c1de521ea2e6173742 and should not show this message "ImportError: dnn not available"

**Comment by voreiche** [comment]
The init file for Theano (.theanorc) was missing in my $HOME.
The contents should be:
`[global]`
`floatX = float32`
`device = gpu`

Now everything is working well!!!.  Thanks alot!!
